const fs = require("fs");
const path = require("path");

// Curated user-guide grouping. The same structure is used for the current
// (develop) docs via sidebars.js and for every materialized version via
// scripts/prepare-versioned-docs.js, so the sidebar looks consistent across
// the version dropdown instead of only on develop.
const USER_GUIDE_CATEGORIES = [
  { label: "Getting Started", items: ["user/intro", "user/quickstart", "user/faq"] },
  {
    label: "Authoring Workflows",
    items: [
      "user/variables",
      "user/artifacts",
      "user/backends",
      "user/operators",
      "user/resources",
      "user/replicas",
      "user/probes",
    ],
  },
  { label: "Outputs & Storage", items: ["user/outputs", "user/results", "user/uploads"] },
  { label: "Composition & Scale", items: ["user/modular-workflows"] },
  { label: "Reference", items: ["user/quick-reference", "user/configuration", "user/cli", "user/architecture"] },
  { label: "Examples", items: ["user/samples"] },
];

// Top-level doc folders rendered as autogenerated sections (after the user guide).
// `plc` is intentionally excluded from the site (see docusaurus.config.js `exclude`).
const AUTOGEN_SECTIONS = ["developer", "release_notes"];
const EXCLUDED_DIRS = new Set(["plc"]);

function listUserDocIds(docsDir) {
  const userDir = path.join(docsDir, "user");
  if (!fs.existsSync(userDir)) return [];
  return fs
    .readdirSync(userDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.mdx?$/.test(entry.name))
    .map((entry) => "user/" + entry.name.replace(/\.mdx?$/, ""));
}

function dirHasDocs(docsDir, dir) {
  const root = path.join(docsDir, dir);
  if (!fs.existsSync(root)) return false;
  const stack = [root];
  while (stack.length) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        stack.push(path.join(current, entry.name));
      } else if (/\.mdx?$/.test(entry.name)) {
        return true;
      }
    }
  }
  return false;
}

// Build the `docs` sidebar from the docs that actually exist in `docsDir`.
// Curated categories only list docs present in this snapshot, empty categories
// are dropped, any uncategorized user docs land under "More", and autogenerated
// sections are only added when their folder exists -- so an older version with a
// different doc set can never reference a missing id or hide a page.
function buildDocsSidebar(docsDir) {
  const userDocs = listUserDocIds(docsDir);
  const userDocSet = new Set(userDocs);
  const used = new Set();

  const categories = [];
  for (const category of USER_GUIDE_CATEGORIES) {
    const items = category.items.filter((id) => userDocSet.has(id));
    items.forEach((id) => used.add(id));
    if (items.length) {
      categories.push({ type: "category", label: category.label, collapsed: false, items });
    }
  }

  const leftovers = userDocs.filter((id) => !used.has(id)).sort();
  if (leftovers.length) {
    categories.push({ type: "category", label: "More", collapsed: false, items: leftovers });
  }

  const sidebar = [];
  if (categories.length) {
    sidebar.push({ type: "category", label: "Sflow User Guide", collapsed: false, items: categories });
  }
  // Agent Skills: a labeled category wrapping the autogenerated agents/ tree,
  // present only when this snapshot ships the skills mirror.
  if (dirHasDocs(docsDir, "agents")) {
    sidebar.push({
      type: "category",
      label: "Agent Skills",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "agents" }],
    });
  }
  for (const dir of AUTOGEN_SECTIONS) {
    if (!EXCLUDED_DIRS.has(dir) && dirHasDocs(docsDir, dir)) {
      sidebar.push({ type: "autogenerated", dirName: dir });
    }
  }

  // Unknown-shaped snapshot: fall back to whole-tree autogeneration so the build
  // never fails and every doc still shows up.
  if (!sidebar.length) {
    return [{ type: "autogenerated", dirName: "." }];
  }
  return sidebar;
}

module.exports = {
  USER_GUIDE_CATEGORIES,
  AUTOGEN_SECTIONS,
  EXCLUDED_DIRS,
  listUserDocIds,
  dirHasDocs,
  buildDocsSidebar,
};
