const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const os = require("os");
const path = require("path");

const { buildDocsSidebar } = require("./sidebarsConfig");

function makeDocs(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "sflow-sidebar-"));
  files.forEach(function (rel) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, "# doc\n");
  });
  return dir;
}

test("groups user docs, keeps only existing ones, and buckets the rest under More", () => {
  const dir = makeDocs([
    "user/intro.md",
    "user/quickstart.md",
    "user/faq.md",
    "user/backends.md",
    "user/probes.md",
    "user/samples.md",
    "user/zzz-extra.md",
    "agents/intro.md",
    "developer/note.md",
    "release_notes/v.md",
    "plc/sflow_srd.md",
  ]);

  assert.deepEqual(buildDocsSidebar(dir), [
    {
      type: "category",
      label: "Sflow User Guide",
      collapsed: false,
      items: [
        { type: "category", label: "Getting Started", collapsed: false, items: ["user/intro", "user/quickstart", "user/faq"] },
        { type: "category", label: "Authoring Workflows", collapsed: false, items: ["user/backends", "user/probes"] },
        { type: "category", label: "Examples", collapsed: false, items: ["user/samples"] },
        { type: "category", label: "More", collapsed: false, items: ["user/zzz-extra"] },
      ],
    },
    {
      type: "category",
      label: "Agent Skills",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "agents" }],
    },
    { type: "autogenerated", dirName: "release_notes" },
  ]);
});

test("never includes the excluded plc or developer directories and falls back when nothing matches", () => {
  const dir = makeDocs(["plc/sflow_srd.md", "developer/note.md"]);
  assert.deepEqual(buildDocsSidebar(dir), [{ type: "autogenerated", dirName: "." }]);
});
