# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Shared helpers for per-task log offload.

Offload takes the sflow driver out of the per-line byte path for a task's logs:
instead of the launcher pumping the subprocess output line-by-line, the execution
substrate writes ``<task>.log`` itself and a compute-side prefixer reproduces
sflow's log format. The mechanism differs per operator:

- srun: ``--output`` (slurmstepd writes the file remotely); no shell redirect.
- bash/local and docker: a shell ``> <file>`` redirect on the driver host.

In all cases the task's merged stdout/stderr is piped through the same prefixer,
which reproduces ``logging.Formatter``'s default asctime byte-for-byte (including
milliseconds) and folds the Slurm rank when present (``$SLURM_PROCID``) so the
offloaded file matches the driver-written stream-mode format.
"""

from __future__ import annotations

import os
import shlex
import sys
from collections.abc import Mapping
from pathlib import Path

# Per-invocation override channel for the offload, set by the
# ``--offload-task-logs/--no-offload-task-logs`` CLI flag (or manually). Takes
# precedence over the per-operator/per-backend config so it can be toggled per
# invocation without editing recipes. The legacy Slurm-specific name is still
# recognized for backwards compatibility.
OFFLOAD_TASK_LOGS_ENV = "SFLOW_OFFLOAD_TASK_LOGS"
LEGACY_OFFLOAD_TASK_LOGS_ENV = "SFLOW_SLURM_OFFLOAD_TASK_LOGS"


def offload_env_override() -> bool | None:
    """Return the env-channel offload decision, or None when unset."""
    raw = os.environ.get(OFFLOAD_TASK_LOGS_ENV)
    if raw is None:
        raw = os.environ.get(LEGACY_OFFLOAD_TASK_LOGS_ENV)
    if raw is None:
        return None
    return raw.strip().lower() in ("1", "true", "yes", "on")


def stdout_is_tty() -> bool:
    try:
        return bool(sys.stdout.isatty())
    except Exception:
        return False


def offload_enabled(log_to_file: bool) -> bool:
    """Resolve whether a task offloads its log.

    Precedence: env channel (CLI flag) > operator config > off. In an interactive
    TTY/--tui session we keep streaming task output to the console (offload is
    file-only), so offload auto-falls back to stream mode; a file-tailer could
    lift this in the future.
    """
    override = offload_env_override()
    enabled = override if override is not None else bool(log_to_file)
    if enabled and stdout_is_tty():
        return False
    return enabled


def task_log_path(envs: Mapping[str, str], task_name: str) -> str | None:
    """Per-task log path the offload writes to, or None if the dir is unknown."""
    task_out = envs.get("SFLOW_TASK_OUTPUT_DIR")
    if not task_out:
        return None
    return os.path.join(str(task_out), f"{task_name}.log")


def unsupported_offload_warning(operator_type: str) -> list[str]:
    """Dry-run hint for operators that do not implement per-task log offload yet.

    Offload is currently implemented for the srun, bash, and docker operators. For
    others (k8s, ssh, python) it is a no-op: when offload is requested globally
    (``--offload-task-logs`` / ``SFLOW_OFFLOAD_TASK_LOGS``) their logs still stream
    through the sflow driver. Returning this from an operator config's
    ``runtime_warnings()`` surfaces that instead of silently ignoring the request.
    """
    if offload_env_override():
        return [
            "per-task log offload was requested "
            f"(--offload-task-logs / {OFFLOAD_TASK_LOGS_ENV}) but the "
            f"'{operator_type}' operator does not support it yet; its logs will "
            "stream through the sflow driver as usual."
        ]
    return []


# Python prefixer materialized once per run. It reproduces logging.Formatter's
# default asctime byte-for-byte ("%Y-%m-%d %H:%M:%S,%03d") so offloaded
# <task>.log lines match the driver-written stream-mode format, including
# milliseconds, and folds the Slurm rank (when set) to mirror srun --label.
LOG_PREFIX_HELPER_SRC = '''\
# Auto-generated by sflow (log offload). Do not edit.
import os
import sys
import time


def main() -> None:
    logger = sys.argv[1] if len(sys.argv) > 1 else "sflow.task"
    rank = os.environ.get("SLURM_PROCID", "")
    rank_prefix = (rank + ": ") if rank != "" else ""
    out = sys.stdout
    for line in iter(sys.stdin.readline, ""):
        line = line.rstrip("\\n")
        now = time.time()
        ts = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(now))
        ts = "%s,%03d" % (ts, int((now % 1) * 1000))
        out.write("%s - %s - INFO - %s%s\\n" % (ts, logger, rank_prefix, line))
        out.flush()


if __name__ == "__main__":
    main()
'''


def ensure_log_prefix_helper(workflow_out_dir: str | None) -> str | None:
    """Materialize the python3 log prefixer once per run; return its path.

    Written under the workflow output dir (shared/visible wherever the task
    runs). Returns None if it cannot be created, so the wrapper falls back to a
    bash prefixer.
    """
    if not workflow_out_dir:
        return None
    try:
        base = Path(workflow_out_dir) / ".sflow"
        base.mkdir(parents=True, exist_ok=True)
        helper = base / "log_prefix.py"
        if not helper.exists():
            helper.write_text(LOG_PREFIX_HELPER_SRC)
        return str(helper)
    except Exception:
        return None


def build_prefixer_pipeline(workflow_out_dir: str | None, task_name: str) -> str:
    """Build the compute-side prefixer (RHS of the offload pipe).

    Prefers the python3 helper (exact millisecond parity); falls back to a
    bash >= 5 EPOCHREALTIME loop (also millis), then a second-resolution
    ``printf '%(...)T'`` loop. The rank ($SLURM_PROCID) is folded into the
    message when set (Slurm) to mirror srun --label; for bash/docker it is unset
    so no rank prefix is added, matching their stream-mode format.
    """
    logger_name = f"sflow.task.{task_name}"
    helper = ensure_log_prefix_helper(workflow_out_dir)
    helper_q = shlex.quote(helper or "")
    logger_q = shlex.quote(logger_name)
    template = (
        '{ LOGGER=__LOGGER__; RANKPFX=""; '
        'if [ -n "${SLURM_PROCID:-}" ]; then RANKPFX="${SLURM_PROCID}: "; fi; '
        'if command -v python3 >/dev/null 2>&1 && [ -f __HELPER__ ]; then '
        'exec python3 __HELPER__ "$LOGGER"; '
        'elif [ -n "${EPOCHREALTIME:-}" ]; then LC_NUMERIC=C; '
        'while IFS= read -r line; do now=$EPOCHREALTIME; sec=${now%.*}; frac=${now#*.}; '
        "printf '%(%Y-%m-%d %H:%M:%S)T,%s - %s - INFO - %s%s\\n' "
        '"$sec" "${frac:0:3}" "$LOGGER" "$RANKPFX" "$line"; done; '
        'else while IFS= read -r line; do '
        "printf '%(%Y-%m-%d %H:%M:%S)T,000 - %s - INFO - %s%s\\n' "
        '-1 "$LOGGER" "$RANKPFX" "$line"; done; fi; }'
    )
    return template.replace("__HELPER__", helper_q).replace("__LOGGER__", logger_q)


def wrap_with_prefixer(
    body: str,
    *,
    workflow_out_dir: str | None,
    task_name: str,
    redirect_to: str | None = None,
) -> str:
    """Wrap a script/command body so its merged stdout/stderr flows through the
    prefixer. The task body's exit status (not the prefixer's) is propagated via
    ``${PIPESTATUS[0]}``; this avoids forcing ``set -o pipefail`` on the user's
    script, which would also change the exit-code semantics of pipelines *inside*
    their own commands. ``redirect_to`` appends a ``> <file>`` redirect for
    operators that write the file via the shell (bash/docker); srun omits it and
    relies on ``--output``.
    """
    prefixer = build_prefixer_pipeline(workflow_out_dir, task_name)
    tail = f" > {shlex.quote(redirect_to)}" if redirect_to else ""
    # The task body ``{ ... }`` is the first element of the pipeline, so
    # ${PIPESTATUS[0]} is its exit status. Exiting with it makes the task's
    # status (not the prefixer's) reach srun/the orchestrator, without the
    # ``set -o pipefail`` side effect of altering the user's own pipelines.
    return (
        "{\n" + body + "\n} 2>&1 | " + prefixer + tail + "\n"
        'exit "${PIPESTATUS[0]}"'
    )
