# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path

from sflow.logging import get_logger
from sflow.core.artifact import Artifact
from sflow.core.artifact_registry import (
    register_artifact_scheme,
    resolve_file_like_uri_to_path,
)

_logger = get_logger(__name__)


class _FileArtifactResolver:
    def resolve(
        self,
        *,
        name: str,
        uri: str,
        description: str | None,
        content: str | None,
        workspace_dir: Path,
        cache_dir: Path,
        output_dir: Path,
        materialize: bool,
        remote_filesystem: bool = False,
        skip_fs_existence_check: bool = False,
    ) -> Artifact:
        path = resolve_file_like_uri_to_path(uri, workspace_dir=workspace_dir)
        is_fs_scheme = str(uri).lower().startswith("fs://")

        # For fs:// artifacts that don't exist, create an empty directory with a warning.
        # This allows workflows to reference output directories that will be populated at runtime.
        if is_fs_scheme and materialize and content is None and not path.exists():
            # Two independent reasons to leave the path alone, deliberately NOT folded
            # into one flag: `remote_filesystem` also decides whether file:// inline
            # content is written on the controller (below), and `--skip-artifact-check`
            # must not reach that -- there is no pod to inject it into on slurm/local,
            # so the content would end up written nowhere at all.
            if remote_filesystem or skip_fs_existence_check:
                why = (
                    "off-host backend"
                    if remote_filesystem
                    else "--skip-artifact-check"
                )
                _logger.info(
                    f"Artifact '{name}' fs:// path '{path}' is treated as a remote "
                    f"path ({why}); not created or validated locally."
                )
            else:
                _logger.warning(
                    f"Artifact '{name}' path does not exist: {path}. "
                    f"Creating empty directory."
                )
                path.mkdir(parents=True, exist_ok=True)

        # Inline content support: only for file:// URIs (validated by schema, but keep a guard).
        if content is not None:
            if not str(uri).startswith("file://"):
                raise ValueError(
                    "Inline artifact content is only supported for 'file://' URIs"
                )

            # For relative file:// URIs, write generated files under the workflow output
            # directory to keep the workspace clean.
            from urllib.parse import unquote, urlparse

            parsed = urlparse(str(uri))
            raw = unquote((parsed.netloc or "") + (parsed.path or ""))
            relative = not Path(raw).is_absolute()
            if relative:
                # Inline content is GENERATED BY THE RUN, so it belongs inside the run's
                # output directory. `output_dir / raw` does NOT collapse `..`, so a URI
                # like `file://../../x` resolves outside it and writes wherever the user
                # can write -- an arbitrary-file-write primitive when the workflow came
                # from somewhere untrusted, and a plain correctness bug otherwise: a
                # stray `..` puts generated files outside the run dir, where nothing
                # cleans them up and they can clobber the user's own files.
                #
                # Scoped deliberately to this branch. It is NOT safe to confine artifact
                # resolution generally: `fs://` artifacts legitimately point outside any
                # workspace (every production recipe mounts a model from e.g.
                # `fs:///mnt/lustre01/models/...`), so a blanket workspace check would
                # break them. Absolute `file://` URIs are left alone too -- they are an
                # explicit choice by the workflow author, and for off-host backends they
                # name an IN-POD path that is never written on the controller.
                root = output_dir.resolve()
                candidate = (output_dir / raw).resolve()
                if not candidate.is_relative_to(root):
                    raise ValueError(
                        f"Artifact '{name}': uri {uri!r} escapes the workflow output "
                        f"directory ({root}). Inline-content artifacts are generated by "
                        f"the run and must stay inside it -- remove the '..' segments, "
                        f"or use an absolute file:// path if you really mean a fixed "
                        f"location."
                    )
                path = candidate

            if remote_filesystem:
                # The backend executes off the controller host (e.g. Kubernetes): the
                # off-host operator injects the content natively into the pod (e.g. a
                # ConfigMap mounted at this path) from Artifact.content below.
                _logger.info(
                    f"Artifact '{name}' (file://) inline content is injected natively by "
                    f"the off-host backend into the pod; in-task path: {path}"
                )
                # Still keep a copy in the workflow output folder on the controller, for
                # parity with the slurm/local backends, so the generated file (e.g. a
                # helper script) is inspectable on the host. Only for RELATIVE file://
                # (which lands under the output dir); an absolute file:// is an in-pod
                # path we must not create on the controller.
                if materialize and relative:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(content, encoding="utf-8")
            else:
                _logger.info(
                    f"Artifact '{name}' (file://) with inline content will be written to: {path}"
                )
                if materialize:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(content, encoding="utf-8")

        return Artifact(
            name=name, uri=uri, description=description, path=path, content=content
        )


# Register file-like resolvers.
FILE_ARTIFACT_RESOLVER = register_artifact_scheme("file")(
    register_artifact_scheme("fs")(_FileArtifactResolver())
)
